// <auto-generated />
namespace SampleApp.DataModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AlterContentPathCacheKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterContentPathCacheKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201211302242196_AlterContentPathCacheKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
